### ISSUE TITLE
mcr.microsoft.com/dotnet/core/sdk:3.0.100-disco: error MSB6004: The specified task executable location "/" is invalid.

### ISSUE THREAD

**Issue by henalbrod** [dotnet/core#3525]
# mcr.microsoft.com/dotnet/core/sdk:3.0.100-disco: error MSB6004: The specified task executable location "/" is invalid.

I'm trying to configure a Github Actions Workflow using this docker image:

**mcr.microsoft.com/dotnet/core/sdk:3.0.100-disco** 

I'm trying to build a .Net Standard 2.0 class library, it is always resulting in:

**error MSB6004: The specified task executable location "/" is invalid.** 

## Yaml File

```
name: CI

on: [push]

jobs:
  build:

    container: 
      image: mcr.microsoft.com/dotnet/core/sdk:3.0.100-disco

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        dotnet new classlib
        dotnet build

```

## Logs

```
Welcome to .NET Core 3.0!
---------------------
SDK Version: 3.0.100

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
Getting ready...
The template "Class library" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /__w/Blazor.Auth0/Blazor.Auth0/Blazor.Auth0.csproj...
  Restore completed in 749.1 ms for /__w/Blazor.Auth0/Blazor.Auth0/Blazor.Auth0.csproj.

Restore succeeded.

Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 28.33 ms for /__w/Blazor.Auth0/Blazor.Auth0/Blazor.Auth0.csproj.
/usr/share/dotnet/sdk/3.0.100/Roslyn/Microsoft.CSharp.Core.targets(59,5): error MSB6004: The specified task executable location "/" is invalid. [/__w/Blazor.Auth0/Blazor.Auth0/Blazor.Auth0.csproj]

Build FAILED.

/usr/share/dotnet/sdk/3.0.100/Roslyn/Microsoft.CSharp.Core.targets(59,5): error MSB6004: The specified task executable location "/" is invalid. [/__w/Blazor.Auth0/Blazor.Auth0/Blazor.Auth0.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.91
##[error]Process completed with exit code 1.

```
