### ISSUE TITLE
error converting YAML to JSON  [.NET Tutorial - Deploy a microservice to Azure]

### ISSUE THREAD

**Issue by guilhermelionzo** [dotnet/core#4153]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

I tried to run the comand **`kubectl apply -f deploy-myMicroservice.yaml`** and I received this error:

`error: error parsing deploy-myMicroservice.yaml: error converting YAML to JSON: yaml: line 22: could not find expected ':'`

I don't know whether my **deploy-myMicroservice.yaml** file is ok. What should I do?

**Comment by scalablecory** [comment]
Can you provide your yaml? It seems like there's a syntax error in it.

**Comment by guilhermelionzo** [comment]
Hi friend.

It follows the .yaml file. I'm following a Microsoft tutorial to deploy a docker container on azure platform [**https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy**]
```
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mymicroservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mymicroservice
    spec:
      containers:
      - name: mymicroservice
        image: guilhermelionzo/mymicroservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
---
apiVersion: v1
kind: Service
metadata:
  name: mymicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mymicroservice
```
