### ISSUE TITLE
Script tries to downagrade .NET Standard 2.1

### ISSUE THREAD

**Issue by Arkasian** [dotnet/core#4542]
# Issue Title

Script tries to downgrade .NET Standard but it fails.

# General
Your instalator script fails when trying to install packages on deb-based distro - Mint 19.4. 
You missed there __--allow-downgrades__, so it can downagrade to older .NET Standard package of version 2.1.
As far as I remember .NET 3.1 was able to use .NET Standard 2.2 so why are you downgrading to 2.1 on .NET 5?
[Preview image of an issue](https://imgur.com/a/tZiQurN)
Correct me if I am mistaken.
Greetings.

**Comment by dagood** [comment]
.NET Standard 2.1 is the latest version, and .NET Standard 2.2 shouldn't exist. If 2.2 did exist, it would actually install side-by-side with 2.1 and not cause any conflict, because they have different package names, `netstandard-targeting-pack-2.1` and `netstandard-targeting-pack-2.2`. I think what's actually happening for you is a difference between the version of `netstandard-targeting-pack-2.1` you have installed vs. the version that's included with the 5.0 preview tar.gz files. (We redistribute the latest version so that the tar.gz contains everything you need to install the 5.0 preview.)

@Arkasian can you provide some more detail, such as the Linux distro you're using, which package you have installed before running the script, and more complete console output? (Copy paste is much more preferable than a screenshot!)

/cc @leecow @NikolaMilosavljevic

**Comment by Arkasian** [comment]
Sorry, dont have an output, didnt have it at the time of writing the issue either, because I closed terminal just after the fact. There was nothing more than what I showed, just standard log for every installation of .NET Core, and then it printed out what I showed. 
I had installed there .NET Core 2.2.402 SDK and compatible runtime.
dotnet-sdk-2.2, aspnet-runtime-2.2 dotnet-runtime-2.2 and those are all I had installed on my system. I will try reproduce that error again, but Im not sure if I will be able to.

**Comment by TheAngryByrd** [comment]
I just had the same issue crop up on TravisCI: https://travis-ci.org/github/demystifyfp/FsToolkit.ErrorHandling/builds/686310362

My current `.travis.yml` file:

```yml
language: csharp

sudo: false # use the new container-based Travis infrastructure
dist: xenial
dotnet: 3.1.200

before_script:
  - nvm install 10.15.0
  - nvm use 10.15.0
  - npm install
  - mkdir $HOME/dotnet_install && cd $HOME/dotnet_install
  - "curl -H 'Cache-Control: no-cache' -L https://aka.ms/install-dotnet-preview -o install-dotnet-preview.sh"
  - sudo bash install-dotnet-preview.sh

script:
  - dotnet --info
  - ./build.sh RunFableTests

```
