### ISSUE TITLE
Error following Run deployment step (of .NET Tutorial - Deploy a microservice to Azure)

### ISSUE THREAD

**Issue by stjepan** [dotnet/core#4929]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: Windows

Running command of **Run deployment**-step results in following error:
_error: unable to recognize "deploy-myMicroservice.yaml": no matches for kind "Deployment" in version "apps/v1beta1"_

Resolution:
Change apiVersion from `apps/v1beta1` to `apps/v1`

Running same command again will result in new error:
_error: error validating "deploy-myMicroservice.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false_

Resolution:
In kind: Development, inside spec, append following:
```
  selector:
    matchLabels:
      app: mymicroservice
```
Now it should run!

This is how deploy-myMicroservice.yaml should be updated on you page:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymicroservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mymicroservice
    spec:
      containers:
      - name: mymicroservice
        image: [YOUR DOCKER ID]/mymicroservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: mymicroservice
---
apiVersion: v1
kind: Service
metadata:
  name: mymicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mymicroservice
```
