### ISSUE TITLE
error: unable to recognize "deploy-mymicroservice.yaml": no matches for kind "Deployment" in version "apps/v1beta1"

### ISSUE THREAD

**Issue by suraj-dhaneshmishra** [dotnet/core#5027]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by som-nitjsr** [comment]
@suraj-dhaneshmishra 
with aks 1.16  v1Beta api is deprecated please use this code.

apiVersion: apps/v1
kind: Deployment
metadata:

**Comment by suraj-dhaneshmishra** [comment]
Thanks for solution 
New error

service/coremicroservice unchanged
The Deployment "coremicroservice" is invalid:
* spec.selector: Required value
* spec.template.metadata.labels: Invalid value: map[string]string{"app":"coremicroservice"}: `selector` does not match template `labels`

**Comment by som-nitjsr** [comment]
@suraj-dhaneshmishra  it is missing selector
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymicroservice
spec:
  replicas: 1
  **selector:
    matchLabels:
      app: mymicroservice**
  template:
    metadata:
      labels:
        app: mymicroservice
    spec:
      containers:
      - name: mymicroservice
        image: [YOUR DOCKER ID]/mymicroservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
---

**Comment by rbanker** [comment]
Make sure you get your indentation right in the yaml.  With the changes suggested above, this worked for me (Note: resources limits added to make VS Code validation happy):

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mymicroservice
  template:
    metadata:
      labels:
        app: mymicroservice
    spec:
      containers:
      - name: mymicroservice
        image: [YOUR DOCKER ID]/mymicroservice:latest
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.5"
            memory: "100Mi"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
---
apiVersion: v1
kind: Service
metadata:
  name: mymicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mymicroservice

```
