### ISSUE TITLE
Azure DevOps Pipeline doesn't support .NET 6? (VS2019 on windows-latest pool)

### ISSUE THREAD

**Issue by mikeKuester** [dotnet/core#6907]
### Description
I upgraded my project from .NET 5 to .NET 6 and wanted to execute a "build, test and publish" pipeline on Azure DevOps. That fails because the hosted agent does not support .NET 6 by default.
```
pool:
  vmImage: 'windows-latest'
```

I added an UseDotNet task in order to install the .NET 6 SDK which works, but that the build task failed ...

```
- task: UseDotNet@2
  displayName: 'Install .NET 6 SDK'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    performMultiLevelLookup: true
```
telling me, that Visual Studio 2019 does not support .NET 6.

```
##[warning]C:\hostedtoolcache\windows\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(134,5): Warning NETSDK1182: Targeting .NET 6.0 in Visual Studio 2019 is not supported.
```

I tried to set the "Compatible Visual Studio version", but than seems to be ignored:
```
    vsVersion: '17.0.0'
```

I would expect, that after the official release of .NET 6 the "latest" hosted agents would also support this new version.

**Comment by mairaw** [comment]
@richlander who would know about what's supported on the latest images?

I am using vmImage: windows-2022 on my pipeline with .NET 6 SDK and that works for me. I haven't tried with windows-latest yet to see if it would work for me as well. I can give it a try and report back.

**Comment by mikeKuester** [comment]
@mairaw Thank you, if I switch to `windows-2022` the build process starts (and fails later with `NETSDK1152: Found multiple publish output files with the same relative path`). With that host I can also remove the UseDotNet task.

It would be fine, if the `windows-latest` would always work with the actual .NET version ;)

**Comment by mairaw** [comment]
I'm trying to find the owner for this so we can have a definitive answer.

**Comment by RyantheLeon** [comment]
> I'm trying to find the owner for this so we can have a definitive answer.

That'd be great. The UseDotNet task worked for me, but I'd much rather define that I'm using .net 6 in one place (within the project, not also in the pipeline) and for everything else to reference that.

**Comment by dasMulli** [comment]
> telling me, that Visual Studio 2019 does not support .NET 6.

VS 2019 (windows) does not support .NET 6, for example as per the [downloads page of the .NET 6 SDK](https://dotnet.microsoft.com/download/dotnet/6.0):

> Visual Studio support
> Visual Studio 2022 (v17.0)
> Visual Studio 2019 for Mac (v8.10)

How are you building your applicaton? If you use the `- task: DotNetCoreCLI@2` tasks to build your app, you should be fine on the `windows-latest` image. If you use the visual studio build tasks, they will not work (as windows-latest is still VS2019)

> NETSDK1152: Found multiple publish output files with the same relative path

This is likely not related to the build image. Does an equivalent `dotnet publish` command work in your project folder or publishing from your local Visual Studio 2022?

**Comment by mikeKuester** [comment]
Ok, I found this page now [Microsoft-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml) with the installed software on the different hosts.

- Windows Server 2022 with Visual Studio 2022 --> windows-2022 
- Windows Server 2019 with Visual Studio 2019 --> windows-latest OR windows-2019

 **I didn't expect, that the "windows-latest" is no the latest ...** :(  (clean code: meaningful names?)  With that info it's clear.


And your are right, I got the NETSDK1152 error also on a local publish. (I changed the target framework, fixed the bugs, run the tests and than I tried directly the pipeline.) There was an obsolete appsettings.json file in a second project.

With that I run into the next error during the test execution in the pipeline:

```
- task: VSTest@2
  displayName: 'Run tests & publish results"'
  inputs:
    testRunTitle: 'Hardware Independent'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testAssemblyVer2: '$(testDll)'
    codeCoverageEnabled: true
    runInParallel: true
    rerunFailedTests: true
    rerunMaxAttempts: 3
    testFiltercriteria: 'TestCategory~hardware independent'
```

I didn't set "vsTestVersion" which should use again the "latest" Version. But it looks for a `vstest.console from a visual studio installation with version [16.0,17.0)` but couldn't find it?


```
Starting: Run tests & publish results"
==============================================================================
Task         : Visual Studio Test
Description  : Run unit and functional tests (Selenium, Appium, Coded UI test, etc.) using the Visual Studio Test (VsTest) runner. Test frameworks that have a Visual Studio test adapter such as MsTest, xUnit, NUnit, Chutzpah (for JavaScript tests using QUnit, Mocha and Jasmine), etc. can be run. Tests can be distributed on multiple agents using this task (version 2).
Version      : 2.170.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/vstest
==============================================================================
SystemVssConnection exists true
SystemVssConnection exists true
Running tests using vstest.console.exe runner.
======================================================
Test selector : Test assemblies
Test filter criteria : TestCategory~hardware independent
Search folder : D:\a\1\s
Action when minimum tests threshold not met : donothing
Minimum tests expected to be run: 0
VisualStudio version selected for test execution : latest
Attempting to find vstest.console from a visual studio installation with version [16.0,17.0).
Attempting to find vstest.console from a visual studio build tools installation with version [16.0,17.0).
Attempting to find vstest.console from a visual studio installation with version [15.0,16.0).
Attempting to find vstest.console from a visual studio build tools installation with version [15.0,16.0).
##[error]Error: Visual Studio 2015 is not found. Try again with a version that exists on your build agent machine.
Finishing: Run tests & publish results"
``` 

The VSTest@2 doesn't support VS 2022 or 17.0 yet?

> Value is not accepted. Valid values: "latest", "16.0", "15.0", "14.0", "toolsInstaller".

**Comment by mikeKuester** [comment]
Setting `vsTestVersion: '16.0'` doesn't help.  I open an [issue at microsoft/azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues/15499) for that.

**Comment by dasMulli** [comment]
Good to hear about your progress! personally I‘m mostly using the DotNetCLI task as well to run tests and publish result (works for SDK-based test projects)

**Comment by schovan** [comment]
I fixed it adding this to xaml file:

```
steps:
- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
```

**Comment by mikeKuester** [comment]
But you don't use VSBuild or VSTest Task, do you?

**Comment by RyantheLeon** [comment]
> I fixed it adding this to yaml file:
> 
> ```
> steps:
> - task: UseDotNet@2
>   displayName: Use .NET 6.0
>   inputs:
>     packageType: 'sdk'
>     version: '6.0.x'
> ```

I agree that this works, and I'm grateful for it. It'd also be nice to have a more permanent fix. This won't work if there's a .net 6.1, or when .net 7 comes out.

**Comment by schovan** [comment]
> But you don't use VSBuild or VSTest Task, do you?

I use `DotNetCoreCLI@2`.

**Comment by Ogglas** [comment]
Imao .NET 6 SDK should be added to `vmImage: 'windows-latest'` as default. 

It is marked as recommended when downloading .NET and it is the current Long-term support (LTS) version.

https://dotnet.microsoft.com/download/dotnet

**Comment by mikeKuester** [comment]
As long as the latest image is the Windows Server 2019 with Visual Studio 2019 it wouldn't help in all cases, for example VSTasks won't run, because .NET 6 needs VS 2022.

The latest image should always be the lastest and not the second latest.

**Comment by Pentadome** [comment]
What is microsoft doing? Why is `windows-latest` not latest? Why does VSTest ignore visual studio 2022? Why is Dotnet 6 a 'full' release when Microsoft doesn't properly support it?

**Comment by schovan** [comment]
> What is microsoft doing? Why is `windows-latest` not latest? Why does VSTest ignore visual studio 2022? Why is Dotnet 6 a 'full' release when Microsoft doesn't properly support it?

I remember when .Net 5.0 was released, it also did't work without `UseDotNet@2` fix. They fixed it later. I don't remember the exact time.

**Comment by brux88** [comment]
i have the same error

**Comment by davidrevoledo** [comment]
I have the same problem

**Comment by BrendanSluke** [comment]
So at this point `windows-latest` does not default to `windows-2022`, which is needed to build/unit test .NET 6 (C# 10) projects.

Here is a working pipeline that I pulled from these 2 blog posts:
(Azure DevOps - The Feature 'Global Using Directive' is currently in Preview)[https://webdev.box33.net/blog/the-feature-global-using-directive-is-not-supported-net-6][https://webdev.box33.net/blog/the-current-net-sdk-does-not-support-net-6]
(Azure Devops - The current .NET SDK does not support targeting .NET 6.0)[
This is a fully working Azure DevOps pipeline for a .NET 6.0 project using C# 10.0:
```YAML
# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

# Add this Command to Include the .NET 6 SDK
- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

# Add a Command To List the Current .NET SDKs (Sanity Check)
- task: CmdLine@2
  inputs:
    script: 'dotnet --list-sdks'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
```
