### ISSUE TITLE
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.   - The following frameworks were found:       6.0.0 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App] 

### ISSUE THREAD

**Issue by louisjrdev** [dotnet/core#6942]
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.   - The following frameworks were found:       6.0.0 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App] 

I am running into this issue when trying to restore, build and run unit tests for my solution in an Azure pipeline on ubuntu-latest.

**Comment by louisjrdev** [comment]
I have solved this issue already but have raised the issue so that if anyone runs into the same problem they can find this. The solution is to load both versions of the .NET SDK that you need at the start of your pipeline.

```
 - task: UseDotNet@2
      displayName: 'Install .NET 5 SDK'
      inputs:
        version: 5.0.x
        performMultiLevelLookup: true
        includePreviewVersions: true
    - task: UseDotNet@2
      displayName: 'Install .NET 6 SDK'
      inputs:
        version: 6.0.x
        performMultiLevelLookup: true
        includePreviewVersions: true
```
