### ISSUE TITLE
dotnet pack --output is broken in 6.0.* SDK Releases

### ISSUE THREAD

**Issue by stunney** [dotnet/core#8245]
### Description

The following GHA against a solution fails:

```
jobs:
  buildpack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Setup .NET Core
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      uses: actions/setup-dotnet@v3
      with:
      # Versions found here: https://github.com/dotnet/core/tree/main/release-notes/6.0
        dotnet-version: '6.0.*'
    - name: Pack with dotnet
      run: dotnet pack ${{ inputs.SLN }} --output nuget-packages --configuration Release
```

with the following error:
```
Run actions/setup-dotnet@v3
/home/runner/work/_actions/actions/setup-dotnet/v3/externals/install-dotnet.sh --version [6](https://github.com/rtkwlf/SATModels/actions/runs/4297270061/jobs/7490056737#step:4:7).0.200
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Attempting to download using primary link https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.200/dotnet-sdk-6.0.200-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.200/dotnet-sdk-6.0.200-linux-x64.tar.gz
dotnet-install: Installed version is 6.0.200
dotnet-install: Adding to current process PATH: `/usr/share/dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.
```

```
MSBuild version 17.5.0-preview-23061-01+040e2a90e for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
Error: /usr/share/dotnet/sdk/7.0.200/Current/SolutionFile/ImportAfter/Microsoft.NET.Sdk.Solution.targets(36,5): error NETSDK1194: The "--output" option isn't supported when building a solution. [/home/runner/work/MyProject.sln]
Error: Process completed with exit code 1.
```

### Configuration

Linux-x64

### Regression?

With ZERO code changes, this code worked last week.

**Comment by stunney** [comment]
I even tried downgrading to 6.0.200 and the issue exists there too.  Is this tied to the MSBuild version?

**Comment by stunney** [comment]
Looking back in the logs from the last successful build, it appears as though the MSBuild version was updated without our specification:

Failing
```
MSBuild version 17.5.0-preview-23061-01+040e2a90e for .NET
```

Passing
```
MSBuild version 17.4.1+9a89d02ff
```

How do I downgrade MSBuild?

**Comment by Michaelschnabel-DM** [comment]
Same issue here

**Comment by davek-eql** [comment]
Same here.  Following action excerpt that was working 3 days ago now fails with message:

"The "--output" option isn't supported when building a solution."

Which seems to be a 7.0 thing despite 6.0 being specified everywhere in my GHA.

```
env:
  AZURE_FUNCTIONAPP_NAME: 'redacted'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' 
  DOTNET_VERSION: '6.0.x'               

jobs:
  build-and-deploy:
    runs-on: windows-latest 
    environment: prod
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh 
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
```

**Comment by mkalinski93** [comment]
According to the [Docs](https://github.com/actions/setup-dotnet#usage)


<img width="844" alt="image" src="https://user-images.githubusercontent.com/64005967/222650865-c4dd203f-b0aa-4284-88c3-10c4cd6b8f67.png">

We have the same problem. We want to specifically use the version 7.0.103 - but it still uses the latest version. Also we created a global.json file that targets the sdk version... not working. For us - Github actions just died in the second they´ve released the latest .net sdk

**Comment by davek-eql** [comment]
Thank you @mkalinski93 , your solution worked for me!

global.json in root with:
```
{
    "sdk": {
      "version": "6.0.406"
    }
 }
```

and an action yml updated to (commented out previous line for comparison):
```
    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
      #  dotnet-version: ${{ env.DOTNET_VERSION }}
        global-json-file: global.json
```
And build was successful.  Much appreciated :-)
