### ISSUE TITLE
Cache dotnet 6 in azure devops

### ISSUE THREAD

**Issue by ilwj28** [dotnet/core#8737]
Hi, im facing an issue where the pipeline is unable to retrieve the dotnet SDK from the cache but instead downloads it on every build. Im currently using a Microsoft-hosted agent in Azure DevOps.

```
    - task: UseDotNet@2
      displayName: 'Get .net core 6'
      inputs:
        packageType: 'sdk'
        version: '6.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet
```

![image](https://github.com/dotnet/core/assets/144113770/b28cc418-791f-4ee7-99f6-b4b80688d1a6)

Am I missing anything in my yml file?
